# Generated by Django 3.0.6 on 2020-06-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200531_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='due',
        ),
    ]
