# Generated by Django 3.0.7 on 2020-06-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_comments_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
